# Generated by Django 4.0.6 on 2022-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_auto_20220816_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'files_storage',
                'ordering': ['-id'],
            },
        ),
    ]
